name: moor_ffi
description: "Provides sqlite bindings using dart:ffi, including a moor executor"
version: 0.4.0
homepage: https://github.com/simolus3/moor/tree/develop/moor_ffi
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  moor: ">=1.7.0 <3.0.0"
  ffi: ^0.1.3
  collection: ^1.0.0
  meta: ^1.0.2

dev_dependencies:
  test: ^1.6.0
  path: ^1.6.0

flutter:
  plugin:
    # the flutter.plugin key needs to exists so that this project gets recognized as a plugin when imported. We need to
    # get recognized as a plugin so that our build scripts are executed.
    foo: bar